In [1]:
#We apply SVR for the boston dataset
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
names = ('CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX',
         'PTRATIO','B','LSTAT','MEDV')
dataset = pd.read_csv('boston_housingdata.csv',names=names)

In [3]:
#Defining Independent and dependent variables
X = dataset.iloc[:,0:13].values
y = dataset.iloc[:,13].values

In [4]:
#divide the dataset into training and testing dataset
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y,test_size = 0.2,random_state=42)

In [5]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train.reshape(-1,1))

In [6]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

C:\Users\reddys\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [7]:
# Predicting a new result
y_pred = regressor.predict(X_test)
y_pred = sc_y.inverse_transform(y_pred)

In [8]:
from sklearn import metrics
#Mean Absolute Error
mae = metrics.mean_absolute_error(y_test,y_pred)
#Mean Squared Error
mse = metrics.mean_squared_error(y_test,y_pred)
#Root Mean Squared Error -Mostly used error metric
rmse = (np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

In [9]:
rmse#Main parameter of error calculation

3.6061367879622117

In [10]:
mae

2.1101240271337844

In [11]:
mse

13.004222533494417

In [13]:
#After removing the features!!that is age and Indus let us see if we can reduce the RMSE
X1 = dataset.iloc[:,[0,1,3,4,5,7,8,9,10,11,12]].values#after removing waste features
y1 = dataset.iloc[:,13].values

In [14]:
from sklearn.model_selection import train_test_split
X1_train,X1_test,y1_train,y1_test = train_test_split(X1, y1,test_size = 0.2,random_state=42)

In [15]:
from sklearn.preprocessing import StandardScaler
sc_X1 = StandardScaler()
X1_train = sc_X1.fit_transform(X1_train)
X1_test = sc_X1.transform(X1_test)
sc_y1 = StandardScaler()
y1_train = sc_y1.fit_transform(y1_train.reshape(-1,1))

In [16]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X1_train, y1_train)

C:\Users\reddys\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [17]:
# Predicting a new result
y1_pred = regressor.predict(X1_test)
y1_pred = sc_y1.inverse_transform(y1_pred)

In [18]:
from sklearn import metrics
#Mean Absolute Error
mae1 = metrics.mean_absolute_error(y1_test,y1_pred)
#Mean Squared Error
mse1 = metrics.mean_squared_error(y1_test,y1_pred)
#Root Mean Squared Error -Mostly used error metric
rmse1 = (np.sqrt(metrics.mean_squared_error(y1_test,y1_pred)))

In [19]:
rmse1

3.694760970760869

In [20]:
#We see the error for the removal of feature is increasing since the SVR method thinks that every single feature is important for
#the dependent variable

In [21]:
y_pred

array([25.53495868, 31.72690901, 16.09631559, 23.17971845, 16.4201042 ,
       20.69894406, 17.26062822, 15.21593208, 21.72349636, 19.21687413,
       19.72548094, 17.66876082, 14.93492333, 21.37504798, 17.93307848,
       23.44699944, 19.25801372,  9.12350182, 43.41810357, 14.48724893,
       25.20822925, 27.33308947, 14.50705399, 22.84293717, 17.0887402 ,
       17.21254854, 21.36173362, 12.17200558, 19.56909858, 18.8681689 ,
       20.34105556, 23.83053139, 20.06412316, 23.10852551, 15.09244874,
       16.9314876 , 33.0188639 , 20.42772295, 21.84200805, 24.36029922,
       17.127447  , 28.89883326, 43.35684162, 18.66917281, 25.33842631,
       16.22404633, 15.25931413, 25.59399834, 18.93035365, 27.8146078 ,
       18.79584225, 34.72004886, 16.75136625, 24.14686441, 43.78534017,
       22.96810874, 16.45298886, 31.39374897, 24.59619967, 16.94274219,
       26.05983383, 33.58565924, 30.03525082, 18.9479371 , 23.79021859,
       18.51312113, 16.03920232, 23.90985177, 28.97218946, 13.26

In [22]:
y_test

array([23.6, 32.4, 13.6, 22.8, 16.1, 20. , 17.8, 14. , 19.6, 16.8, 21.5,
       18.9,  7. , 21.2, 18.5, 29.8, 18.8, 10.2, 50. , 14.1, 25.2, 29.1,
       12.7, 22.4, 14.2, 13.8, 20.3, 14.9, 21.7, 18.3, 23.1, 23.8, 15. ,
       20.8, 19.1, 19.4, 34.7, 19.5, 24.4, 23.4, 19.7, 28.2, 50. , 17.4,
       22.6, 15.1, 13.1, 24.2, 19.9, 24. , 18.9, 35.4, 15.2, 26.5, 43.5,
       21.2, 18.4, 28.5, 23.9, 18.5, 25. , 35.4, 31.5, 20.2, 24.1, 20. ,
       13.1, 24.8, 30.8, 12.7, 20. , 23.7, 10.8, 20.6, 20.8,  5. , 20.1,
       48.5, 10.9,  7. , 20.9, 17.2, 20.9,  9.7, 19.4, 29. , 16.4, 25. ,
       25. , 17.1, 23.2, 10.4, 19.6, 17.2, 27.5, 23. , 50. , 17.9,  9.6,
       17.2, 22.5, 21.4])

In [23]:
y1_pred#After 2 features are removed

array([26.61095381, 31.97033367, 16.48481376, 22.94776311, 16.35764336,
       21.43665888, 17.82965364, 14.88638122, 21.91943671, 19.25367987,
       21.05885701, 18.95364616, 16.02942991, 20.42998675, 19.24579585,
       22.35693074, 19.76782536,  8.81603407, 43.77307272, 14.77762121,
       23.50206833, 26.21000865, 13.8079066 , 21.06504123, 17.1789039 ,
       17.44449668, 20.98601397, 11.59589119, 20.70049461, 18.63638402,
       21.91858328, 23.27931961, 20.43286061, 23.63981583, 15.10531106,
       16.90462055, 33.01473598, 19.78069728, 21.21012998, 22.99853654,
       15.89839374, 29.63653483, 43.24626958, 18.02874715, 24.92254232,
       16.44497662, 15.41676643, 24.22275737, 18.76720958, 28.26751212,
       20.29377924, 34.38179777, 16.4683406 , 23.52931463, 42.66019382,
       22.47547907, 16.75789371, 31.65743589, 23.67572575, 15.9938077 ,
       25.11555149, 33.89107028, 28.53156747, 17.0223481 , 24.20084346,
       20.26545354, 16.24201693, 23.15301399, 28.6668483 , 13.11

In [24]:
y1_test#After 2 features are removed!!

array([23.6, 32.4, 13.6, 22.8, 16.1, 20. , 17.8, 14. , 19.6, 16.8, 21.5,
       18.9,  7. , 21.2, 18.5, 29.8, 18.8, 10.2, 50. , 14.1, 25.2, 29.1,
       12.7, 22.4, 14.2, 13.8, 20.3, 14.9, 21.7, 18.3, 23.1, 23.8, 15. ,
       20.8, 19.1, 19.4, 34.7, 19.5, 24.4, 23.4, 19.7, 28.2, 50. , 17.4,
       22.6, 15.1, 13.1, 24.2, 19.9, 24. , 18.9, 35.4, 15.2, 26.5, 43.5,
       21.2, 18.4, 28.5, 23.9, 18.5, 25. , 35.4, 31.5, 20.2, 24.1, 20. ,
       13.1, 24.8, 30.8, 12.7, 20. , 23.7, 10.8, 20.6, 20.8,  5. , 20.1,
       48.5, 10.9,  7. , 20.9, 17.2, 20.9,  9.7, 19.4, 29. , 16.4, 25. ,
       25. , 17.1, 23.2, 10.4, 19.6, 17.2, 27.5, 23. , 50. , 17.9,  9.6,
       17.2, 22.5, 21.4])